name: Waka Readme

on:
  workflow_dispatch: # Permite desencadenar manualmente el flujo de trabajo
  schedule:
    # Ejecutar cada 30 minutos (esto puede ser demasiado frecuente, puedes ajustarlo según tus necesidades)
    - cron: '0 0 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2 # Paso para clonar el repositorio en el runner

      - name: Update README with WakaTime Stats
        uses: anmol098/waka-readme-stats@master # Paso para actualizar el README con estadísticas de WakaTime
        with:
          COMMIT_BY_ME: "True" # Muestra los commits realizados por ti
          SHOW_UPDATED_DATE: "True" # Muestra la fecha de la última actualización
          SHOW_LINES_OF_CODE: "True" # Muestra las líneas de código escritas
          SHOW_PROFILE_VIEWS: "True" # Muestra las vistas de perfil
          SHOW_COMMIT: "True" # Muestra los últimos commits
          SHOW_DAYS_OF_WEEK: "True" # Muestra los días de la semana
          SHOW_LANGUAGE: "True" # Muestra los lenguajes de programación utilizados
          SHOW_OS: "True" # Muestra el sistema operativo
          SHOW_PROJECTS: "False" # No muestra proyectos específicos (puedes cambiarlo a "True" si lo deseas)
          SHOW_EDITORS: "True" # Muestra los editores de código utilizados
          SHOW_LANGUAGE_PER_REPO: "True" # Muestra los lenguajes por repositorio
          SHOW_SHORT_INFO: "True" # Muestra información resumida
          SHOW_LOC_CHART: "True" # Muestra un gráfico de líneas de código
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # Proporciona la clave de la API de WakaTime almacenada en secrets
          GH_TOKEN: ${{ secrets.GH_TOKEN }} # Proporciona el token de acceso de GitHub almacenado en secrets
